### ISSUE TITLE
Consider to rollback project to .netstandard 2.0

### ISSUE THREAD

**Issue by Ingerdev** [tmteam/NFun#56]
Unfortunatelly, this project cannot be used with .net framework/.netstandard 2.0.

It is not an issue to multiple standalone projects, but it is certainly an issue to library-like products, which are bound to support clients with .net framework. 

As far as i see, only Memory is used from .netstandard 2.1 in small bunch of places.

**Comment by tmteam** [comment]
It looks reasonable, but we have to accept that it's not forever

In general, NFUN as a library is designed for LTS core versions - 3.1/6.0. Therefore, it is used.net standard 2.1

But I think nothing terrible will happen if we support .net standard 2.0 temporarily. This will allow us to release several releases, which should be enough for users with .net standard 2.0

**Comment by Ingerdev** [comment]
Well, i tried to do so (downgrade to 2.0) and adding System.Memory. Sadly, loads of sugar-like errors popped on (fancy indexers like [^2] or [2..], tuples deconstruction and etc). Should i convert it  and make pull request or you prefer to do so by yourself?

**Comment by tmteam** [comment]
Of course syntactic sugar is not necessary. In most cases Tuples were used because of my laziness to write a separate structure/class. Pull request is more than enough.
