### ISSUE TITLE
 how can use in .netframework 4.5

### ISSUE THREAD

**Issue by huangwei16800** [tmteam/NFun#59]
have method conver  NFun use in .net 4.5 ?

**Comment by tmteam** [comment]
Hi - I checked this feature (run Nfun on `net framework 4.5`).

Context:
If we change the target framework in Nfun.csproj, we will get about 100 errors:
-  Using array range (this can be rewritten)
-  Using tuple (you need to connect System.Valuetype)
-  Using `Array.Empty<T>` - can be rewritten to `new T[0]`

However, this will degrade the code of the original NFun and make problems for future support and development of NFun. So - the answer is " **Yes it is possible to build NFun at `.net framework 4.5`, but in a separate branch/fork.** ". It will not be posted in Nugget, as it is very difficult to maintain both versions

In addition to it, Microsoft has officially stopped supporting .net framework 4.5 for now:
```
Support for .NET Framework versions 4.5.2, 4.6, and 4.6.1 ended on April 26, 2022, so security fixes, updates, and technical support for these versions will no longer be provided
```


NFun now supports `net standard 2.0` (this is `net framework 4.6.2` and higher)

So - do you have the opportunity to upgrade the .net framework to 4.6.2? it will be the easiest way.

If there is no such possibility to upgrade, I can help with building NFun in a separate branch/fork to support `.net framework 4.5`
