### ISSUE TITLE
How to use Dictionary<string,object> or List or Array as variables input?

### ISSUE THREAD

**Issue by Himmelt** [tmteam/NFun#76]
Hello, I want to use an array as the input variable, how can i use the array in the expression?
```c#
var cal = Funny.BuildForCalc<int[], int>();
var result = cal.Calc("array[1]*array[2]", new int[] { 1, 2, 3, 4 });
```

As the same, I want to use dynamic variables collection to do some calc :
```c#
Dictionary<string, int> map = new Dictionary<string, int> {
    { "a", 1 },
    { "b", 2 },
    { "c", 3 }
};
var cal = Funny.BuildForCalc<Dictionary<string, int>, double>();
var lambda = cal.ToLambda("a*b");
var o = lambda(map);
Console.WriteLine(o);
```
In the runtime, I will modify the dictionary to continue calculate the next expression.
How can I do this?
Thanks ！

**Comment by tmteam** [comment]
Hi! When using named variables in nfun, you need to use the input class.

For your case:

```
    record MyInput(int[] Array);

    var cal = Funny.BuildForCalc<MyInput, int>();
    var arrayResult = cal.Calc("array[1]*array[2]", new MyInput(new[] { 1, 2, 3, 4 }));
    Console.WriteLine(arrayResult); //prints 6
``` 

This way we can specify the names of the input variables, including if there are several of them.

# Dynamic variables

To access dynamic variables, as in your example, it is best to use functions:

```
       int MyFunction(string name) => name switch
        {
            "foo" => 42,
            "bar" => 41,
            _ => throw new ArgumentException(name)
        };

        var calc = Funny.WithFunction<string, int>("vars", MyFunction).BuildForCalcConstant();
        var answer = calc.Calc("1 + vars('foo')");
        Console.WriteLine(answer); //prints 43
```

Please note that for this function it is necessary to strictly define the return type, in other words - dynamic type, and or weak type system are not allowed in nfun
