### ISSUE TITLE
How to compare System.Version?

### ISSUE THREAD

**Issue by rouen-sk** [tmteam/NFun#78]
Hey there! I am trying this:

```
using NFun;

var f = Funny    
    .WithFunction<string, Version>("ver", x => Version.Parse(x))
    .BuildForCalc<MyClass, bool>().ToLambda("ClientVersion < ver('2.1.0')");

var u = new MyClass{ ClientVersion = Version.Parse("2.0.0") };

var isOk = f.Invoke(u);

class MyClass
{
    public Version ClientVersion { get; set; }
}
```
but getting `NFun.Exceptions.FunnyParseException: 'Invalid operator call argument: <(T0, T0)->Bool. Expected: T0'`

What am I doing wrong? Thanks!

**Comment by tmteam** [comment]
Hi. Unfortunately you cannot compare `Version` type. You can only compare numeric types and strings. The only workaround that i can imagine - is to serialize it as a string, and compare strings. But i need to think about overriding operators  for such an example
